/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.domainmodel.web.internal;

public class DomainmodelImageProvider {

	public static final String FILE = "icons/model.png";
	public static final String WIZARD = "icons/wizard.png";
}