/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPlayValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.codingpark.piraterobot.play.PlayPackage.eINSTANCE);
		return result;
	}
}
