/*Generated by Xtext*/
package org.codingpark.piraterobot.play.web.contentassist

import org.codingpark.piraterobot.play.web.contentassist.AbstractPlayProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PlayProposalProvider extends AbstractPlayProposalProvider {
}
