/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.domainmodel.web.editor;

public class DomainmodelEditor extends AbstractDomainmodelEditor {
	
	static final String EDITOR_ID = "org.xtext.example.domainmodel.web.editor";
	
	public DomainmodelEditor() {
		super();
	}
}