/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.domainmodel.web.editor;

import org.dslforge.texteditor.BasicTextEditorContributor;

public class DomainmodelActionBarContributor extends BasicTextEditorContributor {

	public DomainmodelActionBarContributor() {
		super();
	}
}