/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.ui.contentassist

import org.codingpark.piraterobot.ui.contentassist.AbstractPlayProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PlayProposalProvider extends AbstractPlayProposalProvider {
}
