/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.arithmetics.web.internal;

public class ArithmeticsImageProvider {

	public static final String FILE = "icons/model.png";
	public static final String WIZARD = "icons/wizard.png";
}