/*
 * generated by Xtext
 */
package org.eclipse.sphinx.examples.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HummingbirdUiModule extends org.eclipse.sphinx.examples.xtext.ui.AbstractHummingbirdUiModule {
	public HummingbirdUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
