/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlayUiModule extends org.codingpark.piraterobot.ui.AbstractPlayUiModule {
	public PlayUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
