/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.domainmodel.web.editor;

public class DomainmodelEditor extends AbstractDomainmodelEditor {

	static final String EDITOR_ID = "org.eclipse.xtext.example.domainmodel.web.editor";

	public DomainmodelEditor() {
		super();
	}
}
