/*
 * generated by Xtext
 */
package org.xtext.example.ui.contentassist

import org.xtext.example.ui.contentassist.AbstractDomainmodelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {
}
