/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.mydsl.web.module;

import com.google.inject.Binder;

public class WebMyDslRuntimeModule extends AbstractWebMyDslRuntimeModule {

	@Override
	public void configure(Binder binder) {
		System.out.println("[DSLFORGE] - Configuring module " + this.getClass().getName());
		super.configure(binder);
	}
}
