/**
 * @Generated by DSLFORGE
 */
package org.codingpark.piraterobot.play.web.internal;

public class PlayImageProvider {

	public static final String FILE = "icons/model.png";
	public static final String WIZARD = "icons/wizard.png";
}