/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.arithmetics.web.module;

import org.dslforge.xtext.common.shared.SharedModule;

import com.google.inject.Binder;

public abstract class AbstractWebArithmeticsRuntimeModule extends SharedModule {

	@Override
	public void configure(Binder binder) {
		System.out.println("[DSLFORGE] - Configuring module " + this.getClass().getName());
		super.configure(binder);
	}
}
