/*
 * generated by Xtext
 */
package org.codingpark.piraterobot;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlayRuntimeModule extends org.codingpark.piraterobot.AbstractPlayRuntimeModule {

}
