/**
 * @Generated by DSLFORGE
 */
package org.eclipse.sphinx.examples.xtext.hummingbird.web.internal;

public class HummingbirdImageProvider {

	public static final String FILE = "icons/model.png";
	public static final String WIZARD = "icons/wizard.png";
}