/*
 * generated by Xtext
 */
package org.eclipse.sphinx.examples.xtext.hummingbird;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HummingbirdRuntimeModule extends org.eclipse.sphinx.examples.xtext.hummingbird.AbstractHummingbirdRuntimeModule {

}
