/*
 * generated by Xtext
 */
package org.eclipse.sphinx.examples.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HummingbirdStandaloneSetup extends HummingbirdStandaloneSetupGenerated{

	public static void doSetup() {
		new HummingbirdStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

