/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.codingpark.piraterobot.ui.internal.PlayActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlayExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlayActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlayActivator.getInstance().getInjector(PlayActivator.ORG_CODINGPARK_PIRATEROBOT_PLAY);
	}
	
}
