/*
 * generated by Xtext
 */
package org.xtext.example.conf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfUiModule extends org.xtext.example.conf.ui.AbstractConfUiModule {
	public ConfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
