/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PlayAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/codingpark/piraterobot/parser/antlr/internal/InternalPlay.tokens");
	}
}
