/*
 * generated by Xtext
 */
package org.codingpark.piraterobot.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.codingpark.piraterobot.services.PlayGrammarAccess;

public class PlayParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PlayGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.codingpark.piraterobot.parser.antlr.internal.InternalPlayParser createParser(XtextTokenStream stream) {
		return new org.codingpark.piraterobot.parser.antlr.internal.InternalPlayParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PlayModel";
	}
	
	public PlayGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlayGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
