/*
 * generated by Xtext
 */
package org.eclipse.sphinx.examples.xtext.ui.contentassist

import org.eclipse.sphinx.examples.xtext.ui.contentassist.AbstractHummingbirdProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class HummingbirdProposalProvider extends AbstractHummingbirdProposalProvider {
}
