/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.domainmodel.web.editor;

import org.dslforge.styledtext.BasicText;
import org.dslforge.xtext.common.BasicXtextEditor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.widgets.Composite;
import org.xtext.example.domainmodel.web.editor.widget.Domainmodel;
import org.xtext.example.domainmodel.web.internal.Activator;

public abstract class AbstractDomainmodelEditor extends BasicXtextEditor {
	
	public AbstractDomainmodelEditor() {
		super();
		setLanguageName(Activator.LANGUAGE_NAME);
		setInjector(Activator.getInstance().getInjector(Activator.LANGUAGE_NAME));
	}
	
	@Override
	protected BasicText createWidget(Composite parent, Font font) {
		Domainmodel domainmodelWidget = new Domainmodel(parent, SWT.FILL);
		GridData textLayoutData = new GridData();
		textLayoutData.horizontalAlignment = SWT.FILL;
		textLayoutData.verticalAlignment = SWT.FILL;
		textLayoutData.grabExcessHorizontalSpace = true;
		textLayoutData.grabExcessVerticalSpace = true;
		domainmodelWidget.setLayoutData(textLayoutData);
		domainmodelWidget.setFont(font);
		domainmodelWidget.setEditable(true);
		return domainmodelWidget;
	}
}