/**
 * @Generated by DSLFORGE
 */
package org.xtext.example.domainmodel.web.editor;

import org.dslforge.texteditor.BasicTextEditorContributor;

public abstract class AbstractDomainmodelActionBarContributor extends BasicTextEditorContributor {

	public AbstractDomainmodelActionBarContributor() {
		super();
	}
}