/**
 * @Generated by DSLFORGE
 */
package org.eclipse.sphinx.examples.xtext.hummingbird.web.editor;

import org.dslforge.texteditor.BasicTextEditorContributor;

public class HummingbirdActionBarContributor extends BasicTextEditorContributor {

	public HummingbirdActionBarContributor() {
		super();
	}
}
