/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.arithmetics.web.module;

import com.google.inject.Binder;

public class WebArithmeticsRuntimeModule extends AbstractWebArithmeticsRuntimeModule {

	@Override
	public void configure(Binder binder) {
		System.out.println("[DSLFORGE] - Configuring module " + this.getClass().getName());
		super.configure(binder);
	}
}
