/*
 * generated by Xtext
 */
package org.xtext.example.conf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfRuntimeModule extends org.xtext.example.conf.AbstractConfRuntimeModule {

}
