/*
* generated by Xtext
*/
package org.xtext.example.conf;

import org.xtext.example.conf.ConfStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConfStandaloneSetup extends ConfStandaloneSetupGenerated{

	public static void doSetup() {
		new ConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

