/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.fowlerdsl.web.internal;

public class StatemachineImageProvider {

	public static final String FILE = "icons/model.png";
	public static final String WIZARD = "icons/wizard.png";
}