/*
 * generated by Xtext
 */
package org.eclipse.sphinx.examples.xtext.hummingbird.ui.contentassist

import org.eclipse.sphinx.examples.xtext.hummingbird.ui.contentassist.AbstractHummingbirdProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HummingbirdProposalProvider extends AbstractHummingbirdProposalProvider {
}
