/*
 * generated by Xtext
 */
package org.xtext.example.conf.ui.contentassist

import org.xtext.example.conf.ui.contentassist.AbstractConfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConfProposalProvider extends AbstractConfProposalProvider {
}
