/**
 * @Generated by DSLFORGE
 */
package org.eclipse.xtext.example.arithmetics.web.editor;

public class ArithmeticsEditor extends AbstractArithmeticsEditor {

	static final String EDITOR_ID = "org.eclipse.xtext.example.arithmetics.web.editor";

	public ArithmeticsEditor() {
		super();
	}
}
