/**
 * @Generated by DSLFORGE
 */
package org.codingpark.piraterobot.play.web.editor;

public class PlayEditor extends AbstractPlayEditor {

	static final String EDITOR_ID = "org.codingpark.piraterobot.play.web.editor";

	public PlayEditor() {
		super();
	}
}
